apiVersion: v1
kind: Service
metadata:
  name: {{ template "hdfs-k8s.namenode.fullname" . }}
  labels:
    app: {{ template "hdfs-k8s.namenode.name" . }}
    chart: {{ template "hdfs-k8s.subchart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "hdfs-k8s.namenode.name" . }}
    release: {{ .Release.Name }}
  clusterIP: None
  ports:
  - port: {{ .Values.global.nameNodePort }}
    name: fs
  - port: {{ .Values.global.nameNodeHttpPort }}
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: ext-{{ template "hdfs-k8s.namenode.fullname" . }}
  labels:
    app: {{ template "hdfs-k8s.namenode.name" . }}
    chart: {{ template "hdfs-k8s.subchart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "hdfs-k8s.namenode.name" . }}
    release: {{ .Release.Name }}
  type: NodePort
  ports:
  - name: fs
    port: {{ .Values.global.nameNodePort }}
    nodePort: {{ .Values.global.externalNameNodePort }} 
  - name: http
    port: {{ .Values.global.nameNodeHttpPort }}
    nodePort: {{ .Values.global.externalNameNodeHttpPort }}
